EXECUTE TICKET_INSERT(P_PRICE  => 110 /*IN NUMBER*/, P_PURCHASE_DATE  => TO_DATE('2022/05/10', 'yyyy/mm/dd') /*IN DATE*/, P_ARRIVAL_STATION_ID  => 2 /*IN NUMBER(38)*/,P_DEPARTURE_STATION_ID  => 22/*IN NUMBER(38)*/)

EXECUTE TICKET_INSERT(P_PRICE  => 80 /*IN NUMBER*/, P_PURCHASE_DATE  => TO_DATE('2022/05/10', 'yyyy/mm/dd') /*IN DATE*/, P_ARRIVAL_STATION_ID  => 23 /*IN NUMBER(38)*/,P_DEPARTURE_STATION_ID  => 22/*IN NUMBER(38)*/)

ярославский молоди
EXECUTE TICKET_INSERT(P_PRICE  => 80 /*IN NUMBER*/, P_PURCHASE_DATE  => TO_DATE('2022/05/10', 'yyyy/mm/dd') /*IN DATE*/, P_ARRIVAL_STATION_ID  => 1 /*IN NUMBER(38)*/,P_DEPARTURE_STATION_ID  => 28/*IN NUMBER(38)*/)
283 львовская
EXECUTE TICKET_INSERT(P_PRICE  => 20 /*IN NUMBER*/, P_PURCHASE_DATE  => TO_DATE('2022/05/09', 'yyyy/mm/dd') /*IN DATE*/, P_ARRIVAL_STATION_ID  => 24 /*IN NUMBER(38)*/,P_DEPARTURE_STATION_ID  => 21/*IN NUMBER(38)*/)
