EXECUTE LINK_INSERT(P_IN_ID  => 26 /*IN NUMBER(38)*/,P_OUT_ID  => 30 /*IN NUMBER(38)*/,P_TRAVEL_TIME  => 2 /*IN NUMBER(38)*/)
EXECUTE LINK_INSERT(P_IN_ID  => 27 /*IN NUMBER(38)*/,P_OUT_ID  => 30 /*IN NUMBER(38)*/,P_TRAVEL_TIME  => 3.5 /*IN NUMBER(38)*/)
EXECUTE LINK_INSERT(P_IN_ID  => 28 /*IN NUMBER(38)*/,P_OUT_ID  => 30 /*IN NUMBER(38)*/,P_TRAVEL_TIME  => 4 /*IN NUMBER(38)*/)
EXECUTE LINK_INSERT(P_IN_ID  => 29 /*IN NUMBER(38)*/,P_OUT_ID  => 30 /*IN NUMBER(38)*/,P_TRAVEL_TIME  => 1.5 /*IN NUMBER(38)*/)


EXECUTE LINK_UPDATE(P_ID  => 29 /*IN NUMBER(38)*/, P_IN_ID  => 29 /*IN NUMBER(38)*/, P_OUT_ID  => 28 /*IN NUMBER(38)*/,P_TRAVEL_TIME  => 8 /*IN NUMBER(38)*/)

EXECUTE LINK_UPDATE(P_ID  => 29 /*IN NUMBER(38)*/, P_IN_ID  => 29 /*IN NUMBER(38)*/, P_OUT_ID  => 28 /*IN NUMBER(38)*/,P_TRAVEL_TIME  => 8 /*IN NUMBER(38)*/)