EXECUTE ROUTE_INSERT(P_ROUTE_DATE  => '10-MAY-22', P_NAME  => 'Пригородный маршрут №1' /*IN VARCHAR2*/, P_TRAIN_ID  => 22 /*IN NUMBER(38)*/, P_DIRECTION_ID  => 1 /*IN NUMBER(38)*/)

EXECUTE ROUTE_UPDATE(21,P_ROUTE_DATE  => '10-MAR-22', P_NAME  => 'Пригородный маршрут №2' /*IN VARCHAR2*/, P_TRAIN_ID  => 21 /*IN NUMBER(38)*/, P_DIRECTION_ID  => 1 /*IN NUMBER(38)*/)