EXECUTE POINT_INSERT(P_ARRIVAL_TIME  => '11:00' /*IN VARCHAR2*/,P_DEPARTURE_TIME  => '11:05' /*IN VARCHAR2*/,P_STATION_ID  => 2 /*IN NUMBER(38)*/,P_ROUTE_ID  => 1 /*IN NUMBER(38)*/)
EXECUTE POINT_INSERT(P_ARRIVAL_TIME  => '11:00' /*IN VARCHAR2*/,P_DEPARTURE_TIME  => '11:05' /*IN VARCHAR2*/,P_STATION_ID  => 2 /*IN NUMBER(38)*/,P_ROUTE_ID  => 2 /*IN NUMBER(38)*/)
EXECUTE POINT_UPDATE(1,P_ARRIVAL_TIME  => '11:00' /*IN VARCHAR2*/,P_DEPARTURE_TIME  => '11:05' /*IN VARCHAR2*/,P_STATION_ID  => 23 /*IN NUMBER(38)*/,P_ROUTE_ID  => 1 /*IN NUMBER(38)*/)



EXECUTE POINT_INSERT(P_ARRIVAL_TIME  => '07:00' /*IN VARCHAR2*/,P_DEPARTURE_TIME  => '07:00' /*IN VARCHAR2*/,P_STATION_ID  => 26 /*IN NUMBER(38)*/,P_ROUTE_ID  => 21 /*IN NUMBER(38)*/)
EXECUTE POINT_INSERT(P_ARRIVAL_TIME  => '08:05' /*IN VARCHAR2*/,P_DEPARTURE_TIME  => '08:10' /*IN VARCHAR2*/,P_STATION_ID  => 24 /*IN NUMBER(38)*/,P_ROUTE_ID  => 21 /*IN NUMBER(38)*/)
EXECUTE POINT_INSERT(P_ARRIVAL_TIME  => '08:15' /*IN VARCHAR2*/,P_DEPARTURE_TIME  => '08:20' /*IN VARCHAR2*/,P_STATION_ID  => 1 /*IN NUMBER(38)*/,P_ROUTE_ID  => 21 /*IN NUMBER(38)*/)
EXECUTE POINT_INSERT(P_ARRIVAL_TIME  => '08:30' /*IN VARCHAR2*/,P_DEPARTURE_TIME  => '08:35' /*IN VARCHAR2*/,P_STATION_ID  => 2 /*IN NUMBER(38)*/,P_ROUTE_ID  => 21 /*IN NUMBER(38)*/)
EXECUTE POINT_INSERT(P_ARRIVAL_TIME  => '08:40' /*IN VARCHAR2*/,P_DEPARTURE_TIME  => '08:40' /*IN VARCHAR2*/,P_STATION_ID  => 25 /*IN NUMBER(38)*/,P_ROUTE_ID  => 21 /*IN NUMBER(38)*/)
Каланча 26
Львовка 24
Молоди 1
Столбовая 2
Пл.66 25